aws:
  access-key:
  secret-key:
  dynamodb:

cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-north-1

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    dynamodb:
      entity2ddl:
        auto: validate





