aws:
  access-key: AKIAZHPLDPWLB24GTBW2
  secret-key: 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
  dynamodb:

cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-north-1

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: validate

