package com.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.dynamodb.entity.document.Comment;
import com.dynamodb.entity.document.Document;
import com.dynamodb.model.enums.CustomerType;
import com.dynamodb.model.enums.Priority;
import com.dynamodb.model.enums.Status;
import com.dynamodb.util.LocalDateConverter;
import com.dynamodb.util.LocalDateTimeConverter;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@DynamoDBTable(tableName = "application")
@Data
public class ApplicationEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "ApplicationId")
    private String applicationId;

    @DynamoDBAttribute(attributeName = "RequestId")
    private Long requestId;

    @DynamoDBAttribute(attributeName = "CheckedId")
    private Long checkedId;

    @DynamoDBAttribute(attributeName = "Person")
    private String person;

    @DynamoDBAttribute(attributeName = "CustomerType")
    @DynamoDBTypeConvertedEnum
    private CustomerType customerType;

    @DynamoDBAttribute(attributeName = "CustomerName")
    private String customerName;

    @DynamoDBAttribute(attributeName = "FilePath")
    private String filePath;

    @DynamoDBAttribute(attributeName = "CourtName")
    private String courtName;

    @DynamoDBAttribute(attributeName = "JudgeName")
    private String judgeName;

    @DynamoDBAttribute(attributeName = "DecisionNumber")
    private String decisionNumber;

    @DynamoDBAttribute(attributeName = "Note")
    private String note;

    @DynamoDBAttribute(attributeName = "Status")
    @DynamoDBTypeConvertedEnum
    private Status status;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "BeginDate")
    private LocalDateTime beginDate;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "EndDate")
    private LocalDateTime endDate;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "DecisionDate")
    private LocalDateTime decisionDate;

    @DynamoDBAttribute(attributeName = "IsChecked")
    private Boolean isChecked;

    @DynamoDBAttribute(attributeName = "MailSent")
    private Boolean mailSent;

    @DynamoDBAttribute(attributeName = "Deadline")
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate deadline;

    @DynamoDBAttribute(attributeName = "AssigneeId")
    private Long assigneeId;

    @DynamoDBAttribute(attributeName = "AssigneeName")
    private String assigneeName;

    @DynamoDBAttribute(attributeName = "Priority")
    @DynamoDBTypeConvertedEnum
    private Priority priority;

    @DynamoDBAttribute(attributeName = "Comments")
    private List<Comment> comments;

    @DynamoDBAttribute(attributeName = "StatusHistoryId")
    private String statusHistoryId;

    @DynamoDBAttribute(attributeName = "Documents")
    private List<Document> documents;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "CreatedAt")
    private LocalDateTime createdAt;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "UpdatedAt")
    private LocalDateTime updatedAt;

}
