package com.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.dynamodb.entity.document.BrokenRule;
import com.dynamodb.util.LocalDateTimeConverter;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.List;

@DynamoDBTable(tableName = "status_history")
@Getter
@Setter
public class StatusHistoryEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "StatusHistoryId")
    private String statusHistoryId;

    @DynamoDBAttribute(attributeName = "Response")
    private Long response;

    @DynamoDBAttribute(attributeName = "ErrorMessage")
    private String errorMessage;

    @DynamoDBAttribute(attributeName = "BrokenRules")
    private List<BrokenRule> brokenRules;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "CreatedAt")
    private LocalDateTime createdAt;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "UpdatedAt")
    private LocalDateTime updatedAt;
}
