package com.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.dynamodb.util.LocalDateTimeConverter;

import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "employee")
public class Employee {

    String id;
    LocalDateTime createdAt;
    String name;
    List<Account> account;

   // Date lastUpdatedDate;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "CreatedAt")
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

/* @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getReleaseDateTime() {
        return releaseDateTime;
    }
    public void setReleaseDateTime(LocalDateTime releaseDateTime) {
        this.releaseDateTime = releaseDateTime;
    }*/

    //enum
    /*
     @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private MemberStatus status;
     */
    @DynamoDBAttribute(attributeName = "Account")
    public List<Account> getAccount() {
        return account;
    }

    public void setAccount(List<Account> account) {
        this.account = account;
    }
  /* @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }*/

    
}
